from pathlib import Path
from typing import Dict

class PythonAgent:
    """Expert agent that generates basic Python project structures."""

    def generate_code(self, context: Dict[str, str], dest: Path) -> None:
        """Generate code using provided context.

        Parameters
        ----------
        context : Dict[str, str]
            Arbitrary context describing what to build.
        dest : Path
            Destination directory to store generated files.
        """
        dest.mkdir(parents=True, exist_ok=True)
        main_file = dest / 'main.py'
        with main_file.open('w') as f:
            f.write('# Auto-generated by PythonAgent\n')
            arch = context.get('architecture', 'generic')
            f.write(f"# Architecture: {arch}\n")
            f.write("def main():\n    print('Hello from generated code')\n")
            f.write("\nif __name__ == '__main__':\n    main()\n")
